version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-si
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - lpkia_network

networks:
  lpkia_network:
    external: true
