name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy to Local Server
        run: |
          cd /var/www/lpkia/sisteminformasi
          git pull origin main
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear
